### ISSUE TITLE
Update hardware instructions for thermal sensor

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/rpi.burnin#10]
We've forgotten how to connect the thermal sensors to the Raspberry Pi. Please update the `README.md` for this.

**Comment by LegyPlegy** [comment]
I have included a wiring diagram for the general wiring of the thermistors. I did not make one that included the breakout board that we have for them, since we use it for debugging I thought it would be unnecessary.

**Comment by LegyPlegy** [comment]
updated readme.md with images and explanations for ```therm``` and ```relay```
