### ISSUE TITLE
Thermistor system improvements

### ISSUE THREAD

**Issue by Derek-Colby** [umd-lhcb/rpi.burnin#13]
What we need:
1. Actual thermistor readout, in a separate thread.
2. Simulation of a thermistor readout, in a separate thread. This should have exactly the same interface as the actual readout code, so it can be a drop-in replacement for that, which making testing easier. Additionally, this should have a feed back interface so that the state of the valve will change the readout value.
3. A separate control logic that aims to keep the temperature constant by simulating the states of the valve.

To achieve inter-thread communication, it is recommended to use `queue` library that comes with the standard Python.

**Comment by yipengsun** [comment]
I think with `queue`, the system would looks like this (pseudo code):
```
global_queue

therm_sensor1 -> put_val(global_queue)
therm_sensor2 -> put_val(global_queue)

therm_controller -> read_from(global_queue)
```

Note that sensors and controllers are running in separate threads each. The therm_controller would always listen on the queue to see if there's any new message. If there is, it tries to handle that message immediately. In our case, it would try to turn on the valve in a non-blocking manner.

**Comment by yipengsun** [comment]
@Derek-Colby note that the way we provide feedback to another is **not** thread-safe: If 2 threads tries to update the property of the same thread, it will have undefined behavior.

The solution would be create a lock so that only one thread can update that property at a time.

**Comment by yipengsun** [comment]
The dispatcher model is probably a better way to establish bi-directional communication between threads. Take a look [here](https://sites.google.com/site/hardwaremonkey/blog/python-howtocommunicatebetweenthreadsusingpydispatch)

**Comment by yipengsun** [comment]
An interesting third-party library for dispatcher: https://github.com/scrapy/pypydispatcher

**Comment by yipengsun** [comment]
@Derek-Colby We should try to integrate the thermistor, valve, and data telemetry in the next two weeks.

**Comment by yipengsun** [comment]
This is mostly done and will be tracked elsewhere.
