### ISSUE TITLE
Replicate and improve LVR monitor hardware/software

### ISSUE THREAD

**Issue by CoffeeIntoScience** [umd-lhcb/rpi.burnin#15]
**Overview**
The LVR monitor Raspberry Pi was created for real-time monitoring of the Gen3 LVR outputs, housekeeping voltage rails, and temperatures. This task is to create a "mark 2" version with improved portability and, if possible, mechanical robustness.

The Monitor as it presently exists consists of several pieces

1. Raspberry pi model "1 A+" or newer with 5V adapter
2. Interface (mouse/keyboard/monitor) for raspberry pi
3. 4x ABElectronics ADC Pi (https://www.abelectronics.co.uk/p/69/adc-pi-raspberry-pi-analogue-to-digital-converter) with 1" shrouded right angle headers
4. Custom built harness using 26-gauge stranded PTFE-insulated wire with CGRID-III crimp contacts and 1" housings keyed to match the headers
5. Software based on the libraries available from ABElectronics with modifications by PMH for faster sampling of all 28 channels

**Parts**
For this project, all physical materials except for the crimping tools and contacts will likely need to be purchased. It is probably best to compile a shopping list from Amazon and DigiKey that the Professors can approve and Sally can purchase.

**Improvements**
As noted above, a goal of this is to move beyond simply having a copy to have an improved version. Areas of focus are portability and ground isolation. The Raspberry Pi plugged into a standard 5V micro USB adapter (can be purchased bundled) is a floating ground island. I'd like to keep it that way. One way to do this is a screen powered over a AC/DC converter, as those typically do not have a wall ground connection. Anything you can find powered off of a two-prong cord is essentially what we'd be looking for, give or take. Keep in mind portability is desired. The Raspberry Pi community has a lot of support and ideas floating around, steal steal steal! There's everything from all-in-one screen and keyboard combos to tablet-like interfaces. Ideally you could come up with a couple proposals priced out we could choose from.

The one I had before that broke is https://www.amazon.com/dp/B00Q7BA6E6/?coliid=IAFC4KUVQHC98&colid=1E7GM67MZDCS8&psc=0&ref_=lv_ov_lig_dp_it
If you can find something similar from a reliable brand with better reviews that could work.

The labor-intensive part of this is copying the wiring harness. I will attach a schematic to this issue.

**Comment by CoffeeIntoScience** [comment]
PDF of monitoring harness schematic added to lvr_mon subfolder

**Comment by SummerLeaves** [comment]
Wire Making Note: 
24/72 wires cut and crimped. The 26 AWG wire supply has run out, so this is all that can be made for now.

**Comment by yipengsun** [comment]
Any comments on the progress of this project?

**Comment by SummerLeaves** [comment]
Hi @yipengsun (Sorry for the delayed response! I missed the initial email),

From what I remember of a conversation from the Fall 2019 (or early Spring 2020) semester, Phoebe found a connector that worked without the need to finish the crimping. The rest of the Pi portability issue was secondary to the board assembly project that we worked on in the spring.

**Comment by yipengsun** [comment]
Hmm, let's consider this fixed for now.
