### ISSUE TITLE
Understand when the thermal sensor would return a "85.0" value

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/rpi.burnin#6]
Sometimes thermal sensor would read out a value of "85.0". According to Jorge @LegyPlegy, this value is returned when an error has occurred.

Now if that is an "if and only if", then we if we detect a "85.0", we can just ignore this readout and proceed, thus making ypsun-umd/NeoBurnIn#6 obsolete

**Comment by ypsun-umd** [comment]
My suggestion:
* Temporarily remove the silicone between the legs and make sure the contact is good between the sensor and the wires
* Find a known, reliable thermal sensor that can connect to RPi
* Run our sensor for a few days, and compare the difference between it and the reference, determine how reliable our sensor is---Note that all 85 deg readings should be discarded.

**Comment by ypsun-umd** [comment]
@LegyPlegy Hey Jorge, did I give you another sensor a few weeks ago? If so, can you return it to me, as we need to do some additional testing?

**Comment by LegyPlegy** [comment]
@ypsun-umd It should be on the desk next to the Raspberry Pi station in the undergrad lounge.

**Comment by LegyPlegy** [comment]
After careful analysis and insertion of various print() statements, I figured out the get() function was missing a return statement, which had the unfortunate consequence of leaving the "data" variable to default to "None".

**Comment by LegyPlegy** [comment]
Sensors need more testing to ensure that the "85"s do not occur at all.

Yipeng said they occur about a few times every hour.

**Comment by yipengsun** [comment]
I think this is now a solved problem, because:

1. We've seen output of `None`, which is the expected behavior when non-consecutive 85.0 occurs
2. We decide to average over thermistor readouts. As long as two (or more) thermistors don't fail at the same read operation, the return value will be meaningful.
